version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=core.settings.development
