FROM python:3.10.2-slim-bullseye
ENV PIP_DISABLE_PIP_VERSION_CHECK 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /code

COPY ./djrequirements.txt .

RUN apt-get update -y && \
    apt-get install -y build-essential

RUN pip install --upgrade pip && \
    pip install -r djrequirements.txt

COPY ./entrypoint.dev.sh /code/entrypoint.sh
RUN chmod +x /code/entrypoint.sh

COPY . .

ENTRYPOINT ["/code/entrypoint.sh"]