# Generated by Django 4.2 on 2024-08-23 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='min_purchases_required',
        ),
    ]
