# Generated by Django 4.0.4 on 2024-08-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.ManyToManyField(default='1', related_name='source_country', to='catalogue.country', verbose_name='Source Country'),
        ),
    ]
