# Generated by Django 4.2 on 2024-08-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='source_country',
        ),
        migrations.AddField(
            model_name='product',
            name='source_country',
            field=models.ManyToManyField(related_name='products', to='catalogue.country', verbose_name='Source Country'),
        ),
    ]
