# Generated by Django 4.0.4 on 2024-08-11 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_alter_product_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='country',
        ),
    ]
