# Generated by Django 4.2 on 2024-10-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_product_is_wholesale_product_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='wholesale_quantity_threshold',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wholesale_weight_threshold',
        ),
        migrations.AddField(
            model_name='category',
            name='is_wholesale',
            field=models.BooleanField(default=False, help_text='Indicates if this category is available for wholesale.', verbose_name='Is wholesale'),
        ),
    ]
