# Generated by Django 4.2 on 2024-11-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_remove_product_wholesale_quantity_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='country_icons/', verbose_name='Country Icon'),
        ),
    ]
