# Generated by Django 4.0.4 on 2024-08-13 09:52

import catalogue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='alt_text',
            field=models.ImageField(blank=True, upload_to=catalogue.models.product_image_path, verbose_name='Missing Image'),
        ),
    ]
