# Generated by Django 4.0.4 on 2024-08-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_productimage_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(max_length=100, verbose_name='Missing Image'),
        ),
    ]
