# Generated by Django 4.2 on 2024-11-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_cost', models.IntegerField(default=0, verbose_name='Fixed Delivery Cost')),
                ('free_delivery_threshold', models.IntegerField(default=0, verbose_name='Free Delivery Threshold')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Delivery Setting',
                'verbose_name_plural': 'Delivery Settings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.IntegerField(default=0, verbose_name='Delivery Cost'),
        ),
        migrations.AddField(
            model_name='order',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='order_files/', verbose_name='Attached File'),
        ),
        migrations.AddField(
            model_name='order',
            name='free_delivery',
            field=models.BooleanField(default=False, verbose_name='Free Delivery'),
        ),
    ]
