# Generated by Django 4.2 on 2024-08-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'By cash'), (2, 'By card')], default=1, verbose_name='Payment method'),
        ),
    ]
