# Generated by Django 4.2 on 2024-08-20 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('street_address', models.CharField(max_length=100, verbose_name='Street Address')),
                ('apartment_address', models.CharField(blank=True, max_length=100, verbose_name='Apartment Address')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('shop_name', models.CharField(max_length=255, verbose_name='Shop Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_addresses', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Shop Address',
                'verbose_name_plural': 'Shop Addresses',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('city_ar', models.CharField(max_length=100, null=True, verbose_name='City')),
                ('city_en', models.CharField(max_length=100, null=True, verbose_name='City')),
                ('street_address', models.CharField(max_length=100, verbose_name='Street Address')),
                ('street_address_ar', models.CharField(max_length=100, null=True, verbose_name='Street Address')),
                ('street_address_en', models.CharField(max_length=100, null=True, verbose_name='Street Address')),
                ('apartment_address', models.CharField(blank=True, max_length=100, verbose_name='Apartment Address')),
                ('apartment_address_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apartment Address')),
                ('apartment_address_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apartment Address')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('is_default_for_shipping', models.BooleanField(default=False, verbose_name='Default shipping address?')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='In case we need to call you about your order', max_length=128, region=None, verbose_name='Phone Number')),
                ('notes', models.TextField(blank=True, help_text='Tell us anything we should know when delivering your order.', verbose_name='Delivery Instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('search_text', models.TextField(editable=False, verbose_name='Search text - used only for searching addresses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Shipping Address',
                'verbose_name_plural': 'Shipping Addresses',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('city_ar', models.CharField(max_length=100, null=True, verbose_name='City')),
                ('city_en', models.CharField(max_length=100, null=True, verbose_name='City')),
                ('street_address', models.CharField(max_length=100, verbose_name='Street Address')),
                ('street_address_ar', models.CharField(max_length=100, null=True, verbose_name='Street Address')),
                ('street_address_en', models.CharField(max_length=100, null=True, verbose_name='Street Address')),
                ('apartment_address', models.CharField(blank=True, max_length=100, verbose_name='Apartment Address')),
                ('apartment_address_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apartment Address')),
                ('apartment_address_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apartment Address')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('is_default_for_billing', models.BooleanField(default=False, verbose_name='Default billing address?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_addresses', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Billing Address',
                'verbose_name_plural': 'Billing Addresses',
                'ordering': ('-created_at',),
            },
        ),
    ]
