# Generated by Django 4.2 on 2024-08-21 06:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0003_billingaddress_apartment_address_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='notes_ar',
            field=models.TextField(blank=True, help_text='Tell us anything we should know when delivering your order.', null=True, verbose_name='Delivery Instructions'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='notes_en',
            field=models.TextField(blank=True, help_text='Tell us anything we should know when delivering your order.', null=True, verbose_name='Delivery Instructions'),
        ),
        migrations.AlterUniqueTogether(
            name='billingaddress',
            unique_together={('user', 'postal_code')},
        ),
        migrations.AlterUniqueTogether(
            name='shippingaddress',
            unique_together={('user', 'postal_code')},
        ),
    ]
