# Generated by Django 4.2 on 2024-08-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_shippingaddress_notes_ar_shippingaddress_notes_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopaddress',
            name='apartment_address_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apartment Address'),
        ),
        migrations.AddField(
            model_name='shopaddress',
            name='apartment_address_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apartment Address'),
        ),
        migrations.AddField(
            model_name='shopaddress',
            name='city_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='shopaddress',
            name='city_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='shopaddress',
            name='shop_name_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Shop Name'),
        ),
        migrations.AddField(
            model_name='shopaddress',
            name='shop_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Shop Name'),
        ),
        migrations.AddField(
            model_name='shopaddress',
            name='street_address_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street Address'),
        ),
        migrations.AddField(
            model_name='shopaddress',
            name='street_address_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street Address'),
        ),
    ]
