# Generated by Django 4.2 on 2024-08-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name_ar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name_ar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name_en',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
