# Generated by Django 4.2 on 2024-10-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_user_first_name_remove_user_first_name_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='store_logo',
            field=models.ImageField(blank=True, null=True, upload_to='store_logos'),
        ),
        migrations.AddField(
            model_name='profile',
            name='store_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Store Name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vendor_description',
            field=models.TextField(blank=True, null=True, verbose_name='Vendor Description'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_vendor',
            field=models.BooleanField(default=False, help_text='Designates whether this user is a vendor.', verbose_name='Vendor status'),
        ),
    ]
