# Generated by Django 4.2 on 2024-11-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_profile_store_logo_profile_store_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio_ar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio_en',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='store_logo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='store_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='vendor_description',
        ),
        migrations.AddField(
            model_name='profile',
            name='business_activity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Business Activity'),
        ),
        migrations.AddField(
            model_name='profile',
            name='business_activity_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Business Activity'),
        ),
        migrations.AddField(
            model_name='profile',
            name='business_activity_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Business Activity'),
        ),
        migrations.AddField(
            model_name='profile',
            name='commercial_registration_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Commercial Registration Number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='commercial_registration_number_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Commercial Registration Number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='commercial_registration_number_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Commercial Registration Number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Company Email'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_email_ar',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Company Email'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_email_en',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Company Email'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_name_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Type'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_type_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Type'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_type_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Type'),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth_ar',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth_en',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender_ar',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender_en',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='profile',
            name='manager_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manager Name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='manager_name_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manager Name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='manager_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manager Name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_number_ar',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_number_en',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tax_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tax Number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tax_number_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tax Number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tax_number_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tax Number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AddField(
            model_name='profile',
            name='website_ar',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AddField(
            model_name='profile',
            name='website_en',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
