# Generated by Django 4.2 on 2024-11-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_profile_avatar_remove_profile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_blacklisted',
            field=models.BooleanField(default=False, help_text='Designates whether this user is blacklisted.', verbose_name='Blacklisted'),
        ),
    ]
