# Generated by Django 4.2 on 2024-08-20 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.IntegerField(choices=[(1, 'By cash'), (2, 'By card')], help_text='The method used for payment, such as credit card or PayPal.', verbose_name='Payment method')),
                ('payment_amount', models.IntegerField(default=0, help_text='The total amount paid for the order.', verbose_name='Payment amount')),
                ('payment_date', models.DateTimeField(blank=True, help_text='The date and time when the payment was made.', null=True, verbose_name='Payment date')),
                ('is_paid', models.BooleanField(default=False, help_text='Indicates whether the order has been fully paid.', verbose_name='Order is paid')),
                ('bonus_taken', models.BooleanField(default=False, help_text='Indicates whether any bonus or discount was applied to the payment.', verbose_name='Bonus taken')),
                ('billing_info', models.ForeignKey(blank=True, help_text='The billing information for the user making this payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_info', to='address.billingaddress', verbose_name='User billing info')),
                ('order', models.OneToOneField(help_text='The order associated with this payment.', on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to='order.order', verbose_name='Order')),
                ('shipping_info', models.ForeignKey(blank=True, help_text='The shipping information for the user making this payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_info', to='address.billingaddress', verbose_name='User shipping info')),
            ],
            options={
                'verbose_name': 'payment info',
                'verbose_name_plural': 'Payment infos',
            },
        ),
    ]
