name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and Run Docker Compose
      run: |
        docker-compose up --build -d
        docker-compose run web python manage.py migrate
        docker-compose run web python manage.py test

    - name: Shut down services
      run: docker-compose down
